server:
  port: 8080  # 3000번 포트로 실행

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/taba?characterEncoding=UTF-8&serverTimezone=UTC
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: root # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: 11yhchoa04 # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver